[tool.poetry]
name = "fkie-cve-make-release"
version = "0.1.0"
description = ""
authors = ["Marten Ringwelski <git@maringuu.de>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.scripts]
fkie-cve-make-release = 'fkie_cve_make_release.__main__:main'

[tool.poetry.dependencies]
python = "^3.10"
pygit2 = "^1.14.1"
msgspec = "^0.18.6"

[tool.poetry.group.cli.dependencies]
click = "^8.1.7"
progressbar2 = "^4.4.1"

[tool.poetry.group.dev.dependencies]
datamodel-code-generator = { extras = ["http"], git = "https://github.com/koxudaxi/datamodel-code-generator.git", rev = "00e72040306b2bf3edc2be8f9d28c42f6d28c654" }

pre-commit = "^3.7.1"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9",
    "F",
    "I",
    "PL",
    "UP",
]
ignore = []
fixable = ["ALL"]

[tool.ruff]
exclude = ["fkie_cve_make_release/schema/**"]
