# SPDX-FileCopyrightText: 2024 Fraunhofer FKIE
# SPDX-FileContributor: Marten Ringwelski <git@maringuu.de>
#
# SPDX-License-Identifier: GPL-3.0-only WITH GPL-3.0-linking-exception

[tool.poetry]
name = "nvd-release-builder"
version = "0.1.0"
description = ""
authors = ["Marten Ringwelski <git@maringuu.de>"]
license = "GPL-3.0-or-later"
readme = "README.md"

packages = [
    { include = "nvd_release_builder" },
    { include = "nvd_release_builder_cli" },
]

[tool.poetry.scripts]
nvd-release-builder = 'nvd_release_builder_cli.__main__:main'

[tool.poetry.dependencies]
python = "^3.10"
pygit2 = "^1.14.1"
msgspec = "^0.18.6"

[tool.poetry.group.cli.dependencies]
click = "^8.1.7"
progressbar2 = "^4.4.1"

[tool.poetry.group.dev.dependencies]
datamodel-code-generator = { extras = ["http"], git = "https://github.com/koxudaxi/datamodel-code-generator.git", rev = "00e72040306b2bf3edc2be8f9d28c42f6d28c654" }

pre-commit = "^3.7.1"
reuse = "^3.0.2"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9",
    "F",
    "I",
    "PL",
    "UP",
]
ignore = []
fixable = ["ALL"]

[tool.ruff]
exclude = ["nvd_release_builder/schema/**"]
